#!/bin/bash

cd $(dirname $BASH_SOURCE)

vim -Nu vader.vimrc +Vader*

# vim -Nu vader.vimrc -c 'Vader! *' > /dev/null

# vim -Nu <(cat << EOF
# filetype off
# set rtp+=~/.vim/bundle/vader.vim
# set rtp+=~/.vim/mjm/vim-rook
# filetype plugin indent on
# syntax enable
# EOF) +Vader*
